import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { Loader } from '../components/Loader';

const Detail = () => {
  const { id } = useParams();
  const [data, setData] = useState<any>({})
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true); 
    let setLoadingTimeOut:any = null;
    if(id){
      let getDetail = async() => {
        try {
          let response = await fetch(`/api/v1/post/${id}`, {
            method:"GET",
            headers:{
              'Content-type': 'application/json',
            },
          });
          
          let datas = await response.json();
          setData(datas.data);
          console.log(datas);
        } catch (error) {
          console.log(error);
        }finally{
          setLoadingTimeOut = setTimeout(() => {
            setLoading(false);
          }, 1000);
        };
      };

      getDetail();
    }

    return () => {
      clearTimeout(setLoadingTimeOut);
    }
  }, [id])
  

  return (
    <div className='container max-w-7xl mx-auto w-full min-h-[calc(100vh-70px)] py-[30px]'>
      <h1 className='font-sans font-bold text-2xl mb-4'>Detail Image was generated by OpenAI</h1>
      <div className="py-5 w-full min-h-screen flex flex-col justify-center items-center">
      {
        loading ?
        <Loader/>
        :
        <div className="w-full">
          <p className='font-sans font-normal text-base mb-4'>
            {data.description}
          </p>
          <img src={data.image} alt={data._id} className='w-full h-full max-w-[1024px] object-contain'/>
        </div>
      }
      </div>
    </div>
  )
}

export default Detail
